### ISSUE TITLE
statsapi.web.nhl.com no longer a valid hostname

### ISSUE THREAD

**Issue by nik-field** [thisisevanfox/nhl-my-team-ios-widget#10]
Looks like the NHL has moved to a new API. Documentation here: https://gitlab.com/dword4/nhlapi/-/blob/master/new-api.md

I might fork and migrate the script if I have time.

**Comment by ctlarson17** [comment]
Bumping this issue. 
My widget broke and is giving me the error:
"A server with the specified hostname could not be found."

I am thinking that this API change is the cause of this error... maybe?

**Comment by thisisevanfox** [comment]
I will look into the new API asap. 

@nik-field: Feel free to open a Pull request if you are faster applying the changes,

**Comment by thisisevanfox** [comment]
Hi @nik-field @ctlarson17,
I'm working on the fix right now: https://github.com/thisisevanfox/nhl-my-team-ios-widget/tree/feature/newAPI

**Comment by thisisevanfox** [comment]
Hi @nik-field @ctlarson17,

I just released a new version of the widget. So it should work again! :)

Kind regards
Evan

**Comment by ctlarson17** [comment]
Its working over here. You rock, @thisisevanfox - thank you so much.
