### ISSUE TITLE
Upcoming game dates are incorrect

### ISSUE THREAD

**Issue by zacoh** [thisisevanfox/nhl-my-team-ios-widget#13]
Not sure if I did something wrong in the setup of the new release but the 4 upcoming games at the bottom of the widget don't seem to be accurate. Some upcoming games are missing and for the games that do show up, the dates are wrong.

**Comment by thisisevanfox** [comment]
Hi @zacoh,
I noticed the same thing yesterday, but the next game always seems to be displayed correctly. Thanks for reporting the error. I will try to fix it as soon as possible!

Regards
Evan

**Comment by epifinygirl** [comment]
@thisisevanfox You’re probably already aware but now the main game and the bottom stack have the incorrect dates and games. Right now it’s showing the next game is over a week away.

**Comment by thisisevanfox** [comment]
Hi @zacoh & @epifinygirl,

I finally fixed the bug, now the upcoming games are display correctly again.
