### ISSUE TITLE
Games not showing up anymore because of the new year

### ISSUE THREAD

**Issue by Jimmys098** [thisisevanfox/nhl-my-team-ios-widget#16]
I believe this also occurred back at the end of 2021. I get a blank widget stating “ No upcoming games. Season ended.” Any fixes would be greatly appreciated so I can continue enjoying this great widget/script. Thank you in advance

**Comment by Jimmys098** [comment]
@thisisevanfox

**Comment by thisisevanfox** [comment]
Hi @Jimmys098, can you please check which version of the widget you have installed? Line 7 of the code of the widget. Make sure to use the latest version (currently 5.0.2).

**Comment by Jimmys098** [comment]
@thisisevanfox Ok… That did the job! Thank you for your reply and help. Much appreciated. It’s game on again…
