### ISSUE TITLE
0 updates 

### ISSUE THREAD

**Issue by lennab33** [thisisevanfox/nhl-my-team-ios-widget#19]
![IMG_7681](https://github.com/user-attachments/assets/57ff8fb0-bc48-4b95-abea-d022fd6c9d85)

Mine is like that ! Is that normal because the season has not begun or I have done something wrong ! 
please help me !!

**Comment by thisisevanfox** [comment]
Hi @lennab33,
does the problem still exist? Please refer to the [Installation Guide](https://github.com/thisisevanfox/nhl-my-team-ios-widget/blob/v5.2.0/Installation%20guide.md). If there are any problems, please feel free to reopen this issue.

Kind regards
Evan
