### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by Thecolorblue31** [thisisevanfox/nhl-my-team-ios-widget#21]
![IMG_7184](https://github.com/user-attachments/assets/b2dd1adc-641e-4bf8-9c54-808e9c4d9478)

keep getting this error when running the script

**Comment by zacoh** [comment]
getting the same error

**Comment by GarytheCat93** [comment]
Getting same error

**Comment by Thecolorblue31** [comment]
TSN has a widget now that shows your teams next game and live scores so switching to that

**Comment by GarytheCat93** [comment]
Dman I assume only available in CA? @Thecolorblue31

**Comment by Thecolorblue31** [comment]
No clue. Don’t know of the TSN app is region locked

**Comment by thisisevanfox** [comment]
Hi guys, 

I will have a look at the bug today and solve it. The error is probably due to the fact that there is no data or logo for Utah in my script. Further updates will be posted in #22.

Kind regards,
Evan

**Comment by thisisevanfox** [comment]
Hi guys,

I squashed the bug with #23 and release v5.2.0. For updating please refer to the [Installation Guide](https://github.com/thisisevanfox/nhl-my-team-ios-widget/blob/v5.2.0/Installation%20guide.md).

Thank you for your patience! :)

Kind regards
Evan

CC: @Thecolorblue31, @GarytheCat93
