### ISSUE TITLE
Error on line 760:63: TypeError: undefined is not an object (evaluating 'oTeamData[oData.opponent.abbrev].logo') for "WSH" team only.

### ISSUE THREAD

**Issue by Joelruggles** [thisisevanfox/nhl-my-team-ios-widget#24]
Getting this error below beginning ~ a week ago, and only when attempting to run the script with "WSH" as the defined team. Other script and widget works fine for "SEA".

`2024-11-13 14:34:41: Error on line 760:63: TypeError: undefined is not an object (evaluating 'oTeamData[oData.opponent.abbrev].logo')`

**Comment by thisisevanfox** [comment]
Hi @Joelruggles, that sounds like the problem I fixed with the latest release. Can you please check which version of the widget you have installed? Line 7 of the code of the widget. Make sure to use the latest version (currently 5.2.0).

**Comment by Joelsnug** [comment]
Yep, that did it…could have sworn I was on the latest lol. Thanks :)

**Comment by thisisevanfox** [comment]
Haha, no worries :)
