### ISSUE TITLE
Live scores and skipping to next game.

### ISSUE THREAD

**Issue by Airstandish** [thisisevanfox/nhl-my-team-ios-widget#25]
Hi Evan, my live scores are not working properly even though I have them set to do so. The widget also shows the preview for the next game while the current game is going.

**Comment by thisisevanfox** [comment]
Hi @Airstandish,
Thank you for reporting this issue. It appears to be a duplicate of issue #15. Unfortunately, I don't have a fix for it yet.

Best regards,
Evan
