### ISSUE TITLE
Games not showing up for next year

### ISSUE THREAD

**Issue by usher2005** [thisisevanfox/nhl-my-team-ios-widget#3]
The widget is now blank even when I re-add it 
![D9BD2A5D-C5F0-4634-84EC-36834CDB508A](https://user-images.githubusercontent.com/76718327/147798957-62e4c123-bfdf-48ed-9440-fa396918e33e.jpeg)

**Comment by zacoh** [comment]
Having the same issue

**Comment by usher2005** [comment]
OK so what should we do

**Comment by zacoh** [comment]
I guess we hope @thisisevanfox sees this

**Comment by usher2005** [comment]
I don’t know if he will

**Comment by thisisevanfox** [comment]
Hi @usher2005 and @zacoh,

I think this Problem has something to do with the new year. Tomorrow the widget should work again. If not I'll analyse the issue further.

Regards 
Evan

**Comment by thisisevanfox** [comment]
Hi @usher2005 and @zacoh,

i fixed the issue. Please update your script: https://raw.githubusercontent.com/thisisevanfox/nhl-my-team-ios-widget/v4.0.1/NHL-MyTeam-Widget.js

**Comment by zacoh** [comment]
@thisisevanfox thank you! I just started using the widget and it's awesome. Thanks for all the work

**Comment by usher2005** [comment]
it works again thanks

Hope you can make more for different leagues like CFL, CEBL & WHL here in
Canada and mabey NFL
