### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by zacoh** [thisisevanfox/nhl-my-team-ios-widget#7]
I'm receiving a new error on the widget and it says, "Error: A server with the specified hostname could not be found". Could this be related to the new update to the NHL app?

**Comment by GarytheCat93** [comment]
Same facing the same issue. 

IDK if its internal to my iPhone or w/the NHL API data source

**Comment by zacoh** [comment]
> Same facing the same issue.
> 
> IDK if its internal to my iPhone or w/the NHL API data source

**Comment by zacoh** [comment]
Idk either. Hopefully @thisisevanfox sees this :)

**Comment by GarytheCat93** [comment]
It's working now

Always curious, what was the fix @thisisevanfox if you don't mind sharing! 

Thanks bossman for fixing this! 

Go Bruins lol

**Comment by thisisevanfox** [comment]
Hi,

I debugged it and noticed that the NHL API wasn't reachable. Looks like it was a temporal outage, since it works again now. 

Feel free to reopen the incident when the problem appears again. 

Regards, 
Evan

**Comment by GarytheCat93** [comment]
That error is back again 😭

**Comment by thisisevanfox** [comment]
Hi @GarytheCat93,

please see #9. I think it's a temporal problem again... It should work again soon.

Regards, 
Evan

**Comment by GarytheCat93** [comment]
I still am getting the error :/ 

I'll look into too myself to help assist this week!

Thanks for the awesome code and great work throughout the years
