### ISSUE TITLE
Not an issue but update request for game day

### ISSUE THREAD

**Issue by epifinygirl** [thisisevanfox/nhl-my-team-ios-widget#8]
@thisisevanfox Is it possible to update the script so that if today is game day, it says Today, 7pm @ venue instead of the actual date?

Apologies for creating an issue but wasn’t sure how else to request. Thank you!

**Comment by thisisevanfox** [comment]
Hi @epifinygirl,

I implemented this feature with release 5.0.1. Please update your widget, then it should work.

Kind regards,
Evan
