### ISSUE TITLE
Hostname error

### ISSUE THREAD

**Issue by webeqweens** [thisisevanfox/nhl-my-team-ios-widget#9]
Im recieving the error: a server with the specified hostname could not be found :( Is the NHL API down again or is it me?

**Comment by thisisevanfox** [comment]
Hi, 
I think that is a temporary problem with the NHL API. I get the same error. In the past, the widget would work again after a few hours. I will keep an eye on it.

Thanks for reporting the error!

**Comment by webeqweens** [comment]
It still hasnt fixed itself, is there anything i can do or do i just have to wait it out?

**Comment by thisisevanfox** [comment]
Hi @webeqweens,

the API has changed, so I have to adjust some things in the coding of the widget. I try to look into that asap. Further updates will be posted in issue #10 .

**Comment by thisisevanfox** [comment]
Hi @webeqweens,

I just released a new version of the widget. So it should work again! :)

Kind regards
Evan
